### ISSUE TITLE
Pass config

### ISSUE THREAD

**Issue by Plasmatree** [jeffheaton/mergelife#1]
Hello,
I tried to evolve rules in Python but got a problem in `subprocessScore()`. I found that `config` is not passed to `subprocessScore()`. Adding it as parameter and passing it on call solved the problem:

`def subprocessScore(inputQueue, outputQueue, config): ...`

and in evolve():
`p = mp.Process(target=subprocessScore, args=(inputQueue, outputQueue, config))`

What a great tool! The combination of GOL and GA is something I wanted to try for a long time and you not only provide a scientific paper on it but also working python code. Awsome!

**Comment by jeffheaton** [comment]
Hello @Plasmatree , thank you for that. I will update the code for that.  I am glad you are finding the code useful, and thank you for the bug fix.

**Comment by jeffheaton** [comment]
Added/tested requested change.
